### ISSUE TITLE
Option to reduce height of the editor

### ISSUE THREAD

**Issue by ziming** [lepture/editor#89]
Hi,

The current textarea size is a little too huge, is there an option for me to reduce the height of the editor when creating it?

**Comment by lepture** [comment]
Use CSS:

```css
.CodeMirror {
  height: 200px;
}
```
